# Generated by Django 3.2.18 on 2023-05-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20230511_1845'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstudianteAbs',
        ),
        migrations.DeleteModel(
            name='InstructorAbs',
        ),
        migrations.DeleteModel(
            name='PersonaU',
        ),
    ]
