# Generated by Django 3.2.18 on 2023-05-11 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_comisionmtm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='Fecha de creacion')),
                ('estado', models.IntegerField(choices=[(1, 'Inscripto'), (2, 'Cursando'), (3, 'Egresado')], default=1)),
                ('comision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.comision')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.estudiante')),
            ],
        ),
        migrations.DeleteModel(
            name='ComisionMTM',
        ),
        migrations.AddField(
            model_name='comision',
            name='estudiantes',
            field=models.ManyToManyField(through='administracion.Inscripcion', to='administracion.Estudiante'),
        ),
    ]
